item {
  id: 1
  name: '0.05'
}
item {
  id: 2
  name: '0.50'
}
item {
  id: 3
  name: '1'
}
item {
  id: 4
  name: 'eur002'
}
item {
  id: 5
  name: '5'
}
item {
  id: 6
  name: '10'
}
item {
  id: 7
  name: '20'
}
item {
  id: 8
  name: '50'
}